import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import DashboardLayout from '../../layouts/DashboardLayout'
import { getStoredAgreements } from '../../utils/agreementMockData'
import {
  Button,
  StatusBadge,
  EmptyState,
  Loader,
} from '../../components/ui'
import {
  FileText,
  Download,
  Building2,
  Calendar,
  DollarSign,
  Clock,
  Shield,
  User,
  Info,
  CheckCircle2,
  FileCheck,
} from 'lucide-react'

export default function TenantAgreementPage() {
  const { user } = useAuth()
  const [agreement, setAgreement] = useState(null)
  const [loading, setLoading] = useState(true)
  const [downloadNotice, setDownloadNotice] = useState('')

  const tenantEmail = (user?.email || 'tenant@homesphere.com').toLowerCase().trim()
  const tenantName = (user?.name || 'Elena Rostova').toLowerCase().trim()

  useEffect(() => {
    // Read from shared localStorage agreements source
    const timer = setTimeout(() => {
      const allAgreements = getStoredAgreements()
      // Find agreement matching tenant email or tenant name
      const found = allAgreements.find(
        (a) =>
          (a.tenantEmail || '').toLowerCase().trim() === tenantEmail ||
          (a.tenantName || '').toLowerCase().trim() === tenantName
      )
      setAgreement(found || null)
      setLoading(false)
    }, 200)

    return () => clearTimeout(timer)
  }, [tenantEmail, tenantName])

  const handleDownload = () => {
    setDownloadNotice('Download coming soon.')
    setTimeout(() => {
      setDownloadNotice('')
    }, 3500)
  }

  return (
    <DashboardLayout
      defaultRole="tenant"
      activeItem="agreement"
      pageTitle="Lease Agreement"
    >
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Notice Banner */}
        {downloadNotice && (
          <div className="p-4 rounded-lg bg-[#EAF2F7] border border-[#C2D8E8] text-[#315A7D] text-xs sm:text-sm font-semibold flex items-center justify-between shadow-2xs">
            <div className="flex items-center gap-2">
              <Info className="w-5 h-5 text-[#315A7D] shrink-0" />
              <span>{downloadNotice}</span>
            </div>
            <button
              type="button"
              onClick={() => setDownloadNotice('')}
              className="text-[#315A7D] hover:text-[#274B68] font-bold px-1"
            >
              &times;
            </button>
          </div>
        )}

        {/* Page Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-xl sm:text-2xl font-bold tracking-tight text-[#243447]">
              My Lease Agreement
            </h1>
            <p className="text-xs sm:text-sm text-[#5B6875] mt-1">
              Review your official residential lease terms, payment schedules, and tenure conditions
            </p>
          </div>

          {agreement && (
            <Button
              variant="outline"
              onClick={handleDownload}
              leftIcon={<Download className="w-4 h-4" />}
            >
              Download Agreement
            </Button>
          )}
        </div>

        {/* Loading State */}
        {loading ? (
          <div className="bg-white rounded-lg border border-[#D9E0E6] p-12 shadow-2xs flex justify-center">
            <Loader text="Loading your lease agreement..." size="md" center />
          </div>
        ) : !agreement ? (
          /* Empty State */
          <div className="bg-white rounded-lg border border-[#D9E0E6] p-8 shadow-2xs">
            <EmptyState
              icon={<FileText className="w-8 h-8" />}
              title="No Lease Agreement Found"
              message="You do not currently have an active or drafted residential lease agreement on record. Lease agreements are generated by the property owner once a rental application is approved."
              action={
                <Link to="/tenant/applications">
                  <Button variant="primary" leftIcon={<FileCheck className="w-4 h-4" />}>
                    View My Applications
                  </Button>
                </Link>
              }
            />
          </div>
        ) : (
          /* Agreement Details View */
          <div className="space-y-6">
            {/* Agreement Summary Header Card */}
            <div className="bg-white rounded-lg border border-[#D9E0E6] p-6 shadow-2xs">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-[#D9E0E6] pb-5">
                <div className="flex items-center gap-3.5">
                  <div className="p-3 rounded-md bg-[#EAF2F7] text-[#315A7D] border border-[#D9E0E6]">
                    <FileText className="w-6 h-6" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2.5">
                      <h2 className="text-xl font-bold text-[#243447]">
                        {agreement.agreementNumber}
                      </h2>
                      <StatusBadge status={agreement.status} size="sm" />
                    </div>
                    <p className="text-xs text-[#5B6875] mt-0.5">
                      Primary Tenant: {agreement.tenantName} ({agreement.tenantEmail || tenantEmail})
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    variant="primary"
                    size="sm"
                    onClick={handleDownload}
                    leftIcon={<Download className="w-3.5 h-3.5" />}
                  >
                    Download Agreement
                  </Button>
                </div>
              </div>

              {/* Quick Metrics Grid */}
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-5">
                <div className="p-3.5 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-[#5B6875] block mb-1">
                    Monthly Rent
                  </span>
                  <span className="text-xl font-bold text-[#315A7D]">
                    ${Number(agreement.monthlyRent || 0).toLocaleString()}
                  </span>
                  <span className="text-[11px] text-[#5B6875] block mt-0.5">
                    Due {agreement.rentDueDay || '1st of the month'}
                  </span>
                </div>

                <div className="p-3.5 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-[#5B6875] block mb-1">
                    Security Deposit
                  </span>
                  <span className="text-xl font-bold text-[#243447]">
                    ${Number(agreement.securityDeposit || 0).toLocaleString()}
                  </span>
                  <span className="text-[11px] text-[#3F7D58] font-medium block mt-0.5">
                    Refundable Escrow
                  </span>
                </div>

                <div className="p-3.5 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-[#5B6875] block mb-1">
                    Lease Term
                  </span>
                  <span className="text-sm font-bold text-[#243447] block mt-1">
                    {agreement.startDate}
                  </span>
                  <span className="text-[11px] text-[#5B6875] block">
                    to {agreement.endDate}
                  </span>
                </div>

                <div className="p-3.5 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-[11px] font-semibold uppercase tracking-wider text-[#5B6875] block mb-1">
                    Notice Period
                  </span>
                  <span className="text-xl font-bold text-[#243447]">
                    {agreement.noticePeriod || '30 days'}
                  </span>
                  <span className="text-[11px] text-[#5B6875] block mt-0.5">
                    Prior to Renewal
                  </span>
                </div>
              </div>
            </div>

            {/* Property & Leased Unit Specifications */}
            <div className="bg-white rounded-lg border border-[#D9E0E6] p-6 shadow-2xs space-y-4">
              <h3 className="text-base font-semibold text-[#243447] flex items-center gap-2 border-b border-[#D9E0E6] pb-3">
                <Building2 className="w-4 h-4 text-[#315A7D]" />
                Leased Property & Unit
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-xs text-[#5B6875] block mb-1">Property Name</span>
                  <p className="font-semibold text-[#243447] text-base">
                    {agreement.propertyName}
                  </p>
                </div>

                <div className="p-4 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-xs text-[#5B6875] block mb-1">Designated Unit</span>
                  <p className="font-semibold text-[#243447] text-base">
                    {agreement.unit}
                  </p>
                </div>
              </div>
            </div>

            {/* Financial Schedule & Term Details */}
            <div className="bg-white rounded-lg border border-[#D9E0E6] p-6 shadow-2xs space-y-4">
              <h3 className="text-base font-semibold text-[#243447] flex items-center gap-2 border-b border-[#D9E0E6] pb-3">
                <DollarSign className="w-4 h-4 text-[#3F7D58]" />
                Contract Terms & Rent Schedule
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div>
                  <span className="text-xs text-[#5B6875] block mb-1">Monthly Rent Due Date</span>
                  <p className="font-semibold text-[#243447] text-sm">
                    {agreement.rentDueDay || '1st of the month'}
                  </p>
                </div>

                <div>
                  <span className="text-xs text-[#5B6875] block mb-1">Notice Period For Move-Out</span>
                  <p className="font-semibold text-[#243447] text-sm">
                    {agreement.noticePeriod || '30 days'}
                  </p>
                </div>

                <div>
                  <span className="text-xs text-[#5B6875] block mb-1">Agreement Status</span>
                  <div className="mt-1">
                    <StatusBadge status={agreement.status} size="sm" />
                  </div>
                </div>
              </div>

              {agreement.notes && (
                <div className="mt-4 p-4 rounded-md bg-[#F7F8FA] border border-[#D9E0E6]">
                  <span className="text-xs font-semibold text-[#243447] block mb-1">
                    Notes & Special Provisions
                  </span>
                  <p className="text-xs sm:text-sm text-[#5B6875] leading-relaxed">
                    {agreement.notes}
                  </p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </DashboardLayout>
  )
}
