spring.application.name=rental-management-backend

# Neon PostgreSQL Database

spring.datasource.url=jdbc:postgresql://ep-delicate-forest-a58x744n-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_FhO9IgSm5ZEH

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT

jwt.secret=VGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBSZW50YWwgU3lzdGVt

jwt.expiration=86400000
# AI / ML FastAPI Service
ai.ml.base-url=http://localhost:8000