spring.config.import=optional:file:.env[.properties]

spring.application.name=rental-management-backend

# =========================================================
# Neon PostgreSQL Database
# =========================================================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================

#AWS Connection
aws.region=eu-north-1
aws.s3.bucket-name=rental-management145131187518
aws.access-key-id=${AWS_ACCESS_KEY_ID}

aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}


# JPA / Hibernate
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# =========================================================
# AI / ML FastAPI Services
# =========================================================

ai.ml.base-url=${AI_ML_BASE_URL}

ai.fastapi.rent-prediction-url=${AI_RENT_PREDICTION_URL}

ai.service.maintenance-prediction-url=${AI_MAINTENANCE_PREDICTION_URL}

ai.service.url=${AI_MAINTENANCE_SERVICE_URL}
ai.fastapi.demand-prediction-url=${AI_DEMAND_PREDICTION_URL}
ai.service.payment-risk-url=${AI_PAYMENT_RISK_URL}

sthan.profile.name=${STHAN_PROFILE_NAME}
sthan.profile.password=${STHAN_PROFILE_PASSWORD}
sthan.api.key=${STHAN_API_KEY}

# =========================================================
# Multipart File Upload
# =========================================================

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# =========================================================
# Razorpay
# =========================================================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}